export const SET_PLAYER = "SET_PLAYER";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const UPDATE_QUESTIONS = "UPDATE_QUESTIONS";
export const UPDATE_DIFFICULTY = "UPDATE_DIFFICULTY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
